const exampleQuery = {
  after: null,
  age_recip: 'on',
  answers: [],
  atBeginning: true,
  availability: 'single',
  bodytype: [
    'thin',
    'fit',
    'average',
    'jacked',
    'curvy',
    'full_figured',
    'a_little_extra',
    'overweight',
  ],
  cats: [],
  children: [],
  dogs: [],
  drinking: [],
  drugs: [],
  education: [],
  ethnicity: [],
  fields: 'userinfo,thumbs,percentages,likes,last_contacts,online',
  gender_tags: 1,
  gentation: [54],
  i_want: 'women',
  interest_ids: [],
  languages: 0,
  last_login: 864000,
  limit: 999,
  located_anywhere: 0,
  location: {
    city_name: 'San Francisco',
    country_code: 'US',
    country_name: 'United States',
    default_radius: 25,
    density: 102457,
    display_state: 1,
    latitude: 3777493,
    locid: 4265540,
    longitude: -12241942,
    metro_area: 7360,
    nameid: 170167,
    popularity: 25907,
    postal_code: '94103',
    state_code: 'CA',
    state_name: 'California',
  },
  locid: 4265540,
  looking_for: [],
  lquery: '',
  maximum_age: 27,
  maximum_attractiveness: 10000,
  maximum_height: null,
  minimum_age: 21,
  minimum_attractiveness: 6000,
  minimum_height: null,
  monogamy: 'unknown',
  order_by: 'SPECIAL_BLEND',
  orientation_tags: null,
  personality_filters: {
    adventuresome: 'more',
    independence: 'more',
    introversion: 'less',
    self_confidence: 'more',
  },
  questions: [],
  radius: 50,
  religion: [],
  smoking: [],
  speaks_my_language: false,
  tagOrder: [
    'minimum_attractiveness',
    'maximum_attractiveness',
    'bodytype',
    'availability',
    'personality_filters',
    'speaks_my_language',
  ],
  they_want: 'men',
};
